### ISSUE TITLE
Result of DMENet for comparation

### ISSUE THREAD

**Issue by chanwental** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#10]
Hi Abdullah!

Thanks for your wonderful work!

In this paper, you tested the DMENet on your dataset for comparation.
Could you share the code about it.

Thank you and look forward to your reply!

Best,
chanwental

**Comment by Abdullah-Abuolaim** [comment]
Dear Chanwental,

Thanks for your interest in this project.
You can visit the GitHub repo. of DMENet and find the codes there: https://github.com/codeslake/DMENet

Best,
Abdullah

**Comment by chanwental** [comment]
Hi Abdullah!

I want the implement of deblurring about DMENet rather than the initial code.

Thanks,
chanwental

**Comment by Abdullah-Abuolaim** [comment]
Hi Chanwental,

Could you please reach to Junyong Lee "junyonglee@postech.ac.kr" (the first author of DMENet)?
Junyong Lee shared the code with me earlier.

Thanks,
Abdullah

**Comment by chanwental** [comment]
Thank you. I get it.
