### ISSUE TITLE
how to divide the testing set into Indoor and outdoor scenes

### ISSUE THREAD

**Issue by zhuyeye** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#11]
The paper report the metrics of indoor and outdoor scenes， could you provide the lists of indoor and outdoor scenes in the testing set?

**Comment by Abdullah-Abuolaim** [comment]
Sure, please find at this [[Link](https://drive.google.com/drive/folders/1t-PFwpYfDW-OBPcb5i6RhOoFPzgSzG2S?usp=sharing)] .npy arrays. It is an array of numbers [1,76] where the number indicate the image order when the images are sorted by names.

**Comment by MingzheHu-Duke** [comment]
Hi Abuolaim,

Thank you for your great work.
It seems the link you provided is invalid now. Would you please update the link?
