### ISSUE TITLE
Indoor/Outdoor test results

### ISSUE THREAD

**Issue by dolphin0104** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#12]
First, thanks for your kind work.

When experimenting with the pretrained model you provide, the average psnr result of all test images is the same as reported in the paper. 
However, I don't know why the psnr results for the indoor/outdoor set are different from those reported in the paper.

**Comment by Abdullah-Abuolaim** [comment]
Hello there,

Probably this difference in results is related to the indoor/outdoor labeling. It is better to use the labeling following in the main paper. Please find at this [[Link](https://drive.google.com/drive/folders/1t-PFwpYfDW-OBPcb5i6RhOoFPzgSzG2S?usp=sharing)] .npy arrays. It is an array of numbers [1,76] where the number indicate the image order when the images are sorted by names.

Best,
Abdullah

**Comment by dolphin0104** [comment]
> Hello there,
> 
> Probably this difference in results is related to the indoor/outdoor labeling. It is better to use the labeling following in the main paper. Please find at this [[Link](https://drive.google.com/drive/folders/1t-PFwpYfDW-OBPcb5i6RhOoFPzgSzG2S?usp=sharing)] .npy arrays. It is an array of numbers [1,76] where the number indicate the image order when the images are sorted by names.
> 
> Best,
> Abdullah

Thanks to the list you provided, I solved the problem!
Thank you very much!!
