### ISSUE TITLE
inference own test image

### ISSUE THREAD

**Issue by aaronwutian** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#15]
hi， thanks for your great work。

I want to test your model with my own images, however, i get black output for prediction, do you know what happen?

thanks

**Comment by Abdullah-Abuolaim** [comment]
Hi,

Thanks for your interest in this work. Yes, probably the output you're getting is related to the bit depth data type of the input image. You can try changing the "bit_depth" variable inside the "./DPDNet/config.py" code to be "bit_depth= 8".

Best,
Abdullah
