### ISSUE TITLE
Test on a single RGB image

### ISSUE THREAD

**Issue by xytmhy** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#3]
Dear Dr. Abdullah:

Hi. I have read your paper and thanks for your work. 
I'd like to ask how to test your model on a single image (as I noticed in your ECCV 2020 paper). I'm also doing some research on defocus image deblurring and I hope to use your method as a reference in my paper.  Thanks.

BR.

**Comment by Abdullah-Abuolaim** [comment]
Dear Haoyu Mayer Ma,

Thanks for reaching out.
Yes the method is designed to take two dual-pixel images. To test on the single combined image, we did modify the input layer to take only one image and then retrain.

-Abdullah

**Comment by xytmhy** [comment]
So could you provide a pretrained model of single image deblurring?

**Comment by Abdullah-Abuolaim** [comment]
Sure, please find it at the following link:
https://ln2.sync.com/dl/4f3e0d700/7ingizts-4ffkyxnp-dzdvmfpv-ibk33hzq

All the best!

-Abdullah

**Comment by JuewenPeng** [comment]
Hi, could you please provide the link of pretrained model again? The above link is not available now. Thank you.

**Comment by xytmhy** [comment]
Hi, could you please provide the link of pretrained model again? The above link is not available now. Thank you.

**Comment by Abdullah-Abuolaim** [comment]
Sure, I have updated the link and mad it public again, could you please check it now?
Let me know if it is still not working.

Good luck!

**Comment by JuewenPeng** [comment]
Thanks a lot, it works now.
