### ISSUE TITLE
Requesting for checkpoint of a model trained on 8 bit images

### ISSUE THREAD

**Issue by codeslake** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#4]
Hi Abdullah,

Thanks again for your fabulous work, and
congrat on your acceptance on ECCV2020!

Is it possible for you to share checkpoints for models trained on 8 bit images for both DPDNet and DPDNet_single?

Best,

**Comment by Abdullah-Abuolaim** [comment]
Hi Junyong Lee,

Sure, please find the checkpoint model trained on 8-bit images for DPDNet:
https://ln2.sync.com/dl/68c3fde50/h5thb7u2-3fx8kaxq-h2xkcrgb-2s9cakei

In our experiments, we didn't train a model on 8-bit images for the DPDNet_single. You can try train it, it should be fast and straight forward :-)

Good luck!

Thanks,
Abdullah Abuolaim
