### ISSUE TITLE
mean value pre-claculated in config.py

### ISSUE THREAD

**Issue by chanwental** [Abdullah-Abuolaim/defocus-deblurring-dual-pixel#6]
Hi Abdullah!

Thanks for your wonderful work! 

in _./DPDNet/config.py_, it's mentioned as follows：
_# mean value pre-claculated
src_mean=0
trg_mean=0_.

Is it necessary to calulated the two values when I retrain the model?

Thank you and look forward to your reply!

Best,
Cheng

**Comment by Abdullah-Abuolaim** [comment]
Hi Cheng,

Thanks for your interest in this work and for reaching out.
I used to precompute the mean to make sure the input training data is zero-mean, but with more training it does not change much in the training behavior and then ended up with not subtracting the mean of the training data.
So, you can just leave as it:
_src_mean=0
trg_mean=0_

Thanks,
Abdullah

**Comment by chanwental** [comment]
Thanks very much for your prompt response.
